Discord Link Changes
dmod-gg/dmod pull request #6
Opened 2021-05-07 21:50 UTC by GamerCreator1

Currently the license support the old discord dmod link which lead no where, I changed these link to reflect current changes.

2021-05-08 11:01 UTC, EncryptedDev requested changes

2021-05-08 11:01 UTC, EncryptedDev commented on LICENSE.md
> ++ Dmods Discord: [Discord Link](https://discord.com/invite/VUTu3HyRpN)
Bad English

2021-05-16 21:37 UTC, MattA-Official approved these changes

2021-05-23 20:21 UTC, EncryptedDev commented
*beep boop*, nobody going to resolve this?

2021-05-23 20:28 UTC, merged